### ISSUE TITLE
Deployment failed - 'AppServiceFileAuditLogs' is not supported

### ISSUE THREAD

**Issue by jobmine** [andrewmatveychuk/azure.ghost-web-app-for-containers#5]
Thanks Andrew! Had a problem deploying this solution on Azure. Could you help with this? Thanks!

{"code":"DeploymentFailed","message":"At least one resource deployment operation failed. Please list deployment operations for details. Please see https://aka.ms/DeployOperations for usage details.","details":[{"code":"BadRequest","message":"Category 'AppServiceFileAuditLogs' is not supported."}]}

**Comment by jobmine** [comment]
<img width="1106" alt="Screen Shot 2021-09-22 at 15 49 43" src="https://user-images.githubusercontent.com/5269779/134432223-b928ca46-8563-4300-9b96-427b4b01b856.png">
<img width="859" alt="Screen Shot 2021-09-22 at 15 49 46" src="https://user-images.githubusercontent.com/5269779/134432228-2c28f778-3f26-4256-86c1-584d53046956.png">

{
    "status": "Failed",
    "error": {
        "code": "BadRequest",
        "message": "Category 'AppServiceFileAuditLogs' is not supported."
    }
}

**Comment by andrewmatveychuk** [comment]
@jobmine It seems like the list of available diagnostic logs for Azure web apps has been changed (this feature is currently in preview). I've removed the discontinued log categories from the deployment template.
